### ISSUE TITLE
Links with the readme

### ISSUE THREAD

**Issue by hugohfsouza** [hugohfsouza/GodEye#6]
we need to link the library links with the readme in the session https://github.com/hugohfsouza/GodEye#requirement

**Comment by itsabhianant** [comment]
Hi @hugohfsouza,

I would like to work on this issue but, can you please first tell me that do you want the above link to be added in the readme.md.
If yes then where do you want me to add the link (which line). Also if you give me the details please assign me this issue so that I can start working on it.

**Comment by hugohfsouza** [comment]
Hi @itsabhianant 

It will be a pleasure to have you contributing to our project.

We need to make the library link linked to writing making it easier for people to find the documentation for the libraries used in the project. At the end it is expected that the user will be redirected by clicking on the item in the list of requirements

Here is a list of links for each item in the requirements section:

selênio  - https://pypi.org/project/selenium/
BeautifulSoup - https://pypi.org/project/beautifulsoup4/
configparser - https://pypi.org/project/configparser/
sqlite3  - https://pypi.org/project/db-sqlite3/
